# Generated by Django 4.1.5 on 2023-01-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
