# Generated by Django 4.1.5 on 2023-01-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_app', '0002_subscription_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='members',
        ),
    ]
