# Generated by Django 4.1.5 on 2023-01-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_app', '0003_remove_subscription_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='slots_available',
            field=models.IntegerField(default=0),
        ),
    ]
